import React, { useEffect } from "react";
import FirstHeader from "./firstHeading";
import MainBody from "./mainBody";
import { useRouter } from "next/router";
import { auth} from "../../lib/firebase";
import Head from "next/head";

function Index() {
  const router = useRouter();

  return (
    <>
        <>
          <Head>
            <title>Juaben APS - Parent&apos;s Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>
          <FirstHeader />
          <MainBody />
        </>
 
    </>
  );
}

export default Index;
