import React from "react";
import Head from "next/head";
import styles from "../../styles/choose-portal/index.module.css";
import withSession from "@/lib/session";
import FirstHeader from "./firstHeader";
import Portals from "./portals";
import HomeBody from "./home-body";

function Index({ user }) {
  return (
    <>
      <Head>
        <title>Juaben APS - Choose Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.choosePortalContainer}>
        <FirstHeader user={user} />
        <Portals user={user} />
        <HomeBody user={user} />
      </div>
    </>
  );
}

export default Index;

export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req.session.get("user");
  if (!user) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  if (user) {
    req.session.set("user", user);
    await req.session.save();
  }
  return {
    props: {
      user: user,
    },
  };
});
