import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/admin_portal_css/studentProfilePage.module.css";
import StudentAttendancecomp from "./studentAttendance";
import StudentFeesComp from "./studentFees";
import StudentClassScore from "./individualTest";
import StudentHomework from "./groupWork";
import StudentClassTest from "./studentClassTest";
import UpdateForm from "../update-student";
import { db } from "../../../lib/firebase";
import { ref, remove } from "firebase/database";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import {
  Button,
  Dialog,
  DialogContent,
  DialogTitle,
  IconButton,
} from "@mui/material";
import Menu from "@mui/icons-material/Menu";

function StudentProfilePage({
  hideStudentProfilePage,
  selectedStudent,
  attendance,
}) {
  const [activeComponent, setActiveComponent] = useState("studentProfile");
  const [toggleUpdateForm, setToggleUpdateForm] = useState(false);
  const [openModal, setOpenModal] = useState(false);

  const handleCloseModal = () => {
    setOpenModal(false);
  };

  const navigateToComp = (compName) => {
    setActiveComponent(compName);
  };

  const showUpdateForm = () => {
    setToggleUpdateForm(true);
  };

  const closeUpdateForm = () => {
    setToggleUpdateForm(false);
  };

  const handleRemoveStudent = async () => {
    try {
      await remove(ref(db, `japsstudents/${selectedStudent.key}`));
      toast.success(`Student ${selectedStudent.key} removed successfully`);
      hideStudentProfilePage();
    } catch (error) {
      console.error("Error deleting note:");
    }
  };

  return (
    <>
      <Head>
        <title>Juaben APS - Student Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.profilePageContainer}>
        <div className={styles.profilePageContent}>
          <div className={styles.profilePageHeader}>
            <div className={styles.profileName}>
              <h1>{`Profile - ${selectedStudent?.FirstName} ${selectedStudent?.LastName}`}</h1>
            </div>

            <div className={styles.navContainer}>
              <button onClick={() => navigateToComp("studentProfile")}>
                Profile
              </button>
              <button onClick={() => navigateToComp("studentAttendance")}>
                Attendance
              </button>
              <button onClick={() => navigateToComp("studentClassScore")}>
                Individual Test
              </button>
              <button onClick={() => navigateToComp("studentClassTest")}>
                Class Test
              </button>

              <button onClick={() => navigateToComp("studentClassTest")}>
                Group Work
              </button>

              <button onClick={() => navigateToComp("studentHomework")}>
                Project Work
              </button>
              <button onClick={() => navigateToComp("studentFees")}>
                Fees
              </button>
            </div>
            <div
              className={styles.menuContainer}
            >
              <Menu />
            </div>
          </div>
        </div>

        {activeComponent === "studentProfile" && (
          <div className={styles.profileContainer}>
            <div className={styles.profileItems}>
              <div className={styles.items}>
                <div className={styles.item}>
                  <p>First Name</p>
                  <h1>{selectedStudent?.FirstName}</h1>
                </div>

                <div className={styles.item}>
                  <p>Middle Name</p>
                  <h1>{selectedStudent?.MiddleName}</h1>
                </div>

                <div className={styles.item}>
                  <p>Last Name</p>
                  <h1>{selectedStudent?.LastName}</h1>
                </div>

                <div className={styles.item}>
                  <p>Gender</p>
                  <h1>{selectedStudent?.Gender}</h1>
                </div>

                <div className={styles.item}>
                  <p>Date Of Birth</p>
                  <h1>{selectedStudent?.DOB}</h1>
                </div>

                <div className={styles.item}>
                  <p>Student Number</p>
                  <h1>{selectedStudent?.StudentNumber}</h1>
                </div>

                <div className={styles.item}>
                  <p>Enrollment Date</p>
                  <h1>{selectedStudent?.EnrollmentDate}</h1>
                </div>

                <div className={styles.item}>
                  <p>Student Residence</p>
                  <h1>{selectedStudent?.StudentResidence}</h1>
                </div>

                <div className={styles.item}>
                  <p>Class</p>
                  <h1>{selectedStudent?.Class}</h1>
                </div>

                <div className={styles.item}>
                  <p>NHIS No</p>
                  <h1>{selectedStudent?.NHISno}</h1>
                </div>

                <div className={styles.item}>
                  <p>NHIS Name</p>
                  <h1>{selectedStudent?.NHISName}</h1>
                </div>

                <div className={styles.item}>
                  <p>Guardian&apos;s Name</p>
                  <h1>{selectedStudent?.guardianName}</h1>
                </div>

                <div className={styles.item}>
                  <p>Guardian&apos;s Residence</p>
                  <h1>{selectedStudent?.guardianResidence}</h1>
                </div>

                <div className={styles.item}>
                  <p>Guardian&apos;s Phone</p>
                  <h1>{selectedStudent?.guardianPhone}</h1>
                </div>

                <div className={styles.item}>
                  <p>Guardian&apos;s Other Phone</p>
                  <h1>{selectedStudent?.guardianOtherPhone}</h1>
                </div>
              </div>
            </div>
            <div className={styles.backToList}>
              <button onClick={hideStudentProfilePage}>Back To List</button>
              <button onClick={showUpdateForm}>Edit Profile</button>
              <button onClick={() => setOpenModal(true)}>Remove Student</button>
            </div>
          </div>
        )}
      </div>

      <Dialog open={openModal} onClose={handleCloseModal}>
        <DialogTitle
          style={{ fontSize: "15px", textTransform: "uppercase" }}
        >{`Are you sure you want to delete`}</DialogTitle>
        <DialogContent>
          <ul
            style={{
              textDecoration: "none",
              listStyle: "none",
              fontFamily: "sans-serif",
            }}
          >
            <Button onClick={handleRemoveStudent}>Yes</Button>
            <Button onClick={handleCloseModal}>No</Button>
          </ul>
        </DialogContent>
      </Dialog>

      {activeComponent === "studentAttendance" && (
        <StudentAttendancecomp
          navigateToComp={navigateToComp}
          selectedStudent={selectedStudent}
          attendance={attendance}
          hideStudentProfilePage={hideStudentProfilePage}
        />
      )}

      {activeComponent === "studentFees" && (
        <StudentFeesComp
          navigateToComp={navigateToComp}
          hideStudentProfilePage={hideStudentProfilePage}
          selectedStudent={selectedStudent}
        />
      )}

      {activeComponent === "studentClassScore" && (
        <StudentClassScore
          navigateToComp={navigateToComp}
          selectedStudent={selectedStudent}
          hideStudentProfilePage={hideStudentProfilePage}
        />
      )}

      {activeComponent === "studentClassTest" && (
        <StudentClassTest
          navigateToComp={navigateToComp}
          selectedStudent={selectedStudent}
          hideStudentProfilePage={hideStudentProfilePage}
        />
      )}
      {activeComponent === "studentHomework" && (
        <StudentHomework
          navigateToComp={navigateToComp}
          selectedStudent={selectedStudent}
          hideStudentProfilePage={hideStudentProfilePage}
        />
      )}

      {toggleUpdateForm && (
        <UpdateForm
          closeUpdateForm={closeUpdateForm}
          selectedStudent={selectedStudent}
        />
      )}
      <ToastContainer />
    </>
  );
}

export default StudentProfilePage;
