import React from "react";
import FirstHeader from "./firstHeader";
import MainBody from "./mainBody";
import Head from "next/head";
import withSession from "@/lib/session";

function Index() {
  return (
    <>
      <Head>
        <title>Juaben APS - Teacher&apos;s Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <FirstHeader />
      <MainBody />
    </>
  );
}

export default Index;

export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req.session.get("user");
  if (!user || !user.displayName === "Teacher") {
    return {
      redirect: {
        destination: "/comps/login",
        permanent: false,
      },
    };
  }

  
  if (user) {
    req.session.set("user", user);
    await req.session.save();
  }

  return {
    props: {
      user: user,
    },
  };
});
